apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: boilerr-dev

resources:
  - ../../default

labels:
  - pairs:
      app.kubernetes.io/instance: boilerr-dev
      environment: development

patches:
  - path: deployment_patch.yaml
    target:
      kind: Deployment
      name: controller-manager

images:
  - name: controller
    newName: ghcr.io/craightonh/boilerr
    newTag: main
