{{- if .Values.rbac.create -}}
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: {{ include "boilerr.fullname" . }}-manager-rolebinding
  labels:
    {{- include "boilerr.labels" . | nindent 4 }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: {{ include "boilerr.fullname" . }}-manager-role
subjects:
- kind: ServiceAccount
  name: {{ include "boilerr.serviceAccountName" . }}
  namespace: {{ include "boilerr.namespace" . }}
{{- end }}
