apiVersion: boilerr.dev/v1alpha1
kind: SteamServer
metadata:
  name: valheim-prod
  namespace: game-servers
spec:
  game: valheim
  config:
    serverName:
      value: "Vikings Only"
    worldName:
      value: "Midgard"
    password:
      secretKeyRef:
        name: valheim-secrets
        key: password
    public:
      value: "0"
  storage:
    size: 30Gi
  serviceType: LoadBalancer
